### ISSUE TITLE
Add a ModelAdmin icon other than the default

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverstripe-logviewer#11]
If using something from online, need to attribute in the readme

**Comment by robbieaverill** [comment]
Maybe something like this?

![](https://cdn3.iconfinder.com/data/icons/nature-animals/512/Log_A-512.png)

**Comment by Firesphere** [comment]
I LIKE THAT ONE MUCH! :D 
Brilliantly different from what you'd expect (a paper with lines ;) )
