### ISSUE TITLE
Format JSON part of the error message

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-logviewer#13]
Currently, it's just a plain string. It would be nice if the error could be split up into the following:
```
Fatal Error Something went wrong
{
    "code": 1,
    "file": mysite\src\handler\errorthing.php,
    "line": 21
}
[
    "formatted": array
]
```
To make it more readable.

**Comment by robbieaverill** [comment]
Are you suggesting to format the entire error message into a json structure like that, or parse it and break it up somehow?

**Comment by Firesphere** [comment]
The latter, I'd think. Haven't thought about _how_ exactly yet ;) But for readability, it's a great improvement and can easily be achieved by using `JSON_PRETTY_PRINT` I believe.

**Comment by robbieaverill** [comment]
I like it. I guess it should be configurable and also te default option

**Comment by robbieaverill** [comment]
Reopening - I like this idea
