### ISSUE TITLE
Circular dependency error from a dependency of silverstripe/config

### ISSUE THREAD

**Issue by zanderwar** [silverleague/silverstripe-logviewer#29]
Fresh install of SS4 beta2, I get this error immediately after successful `composer require`

    Uncaught MJS\TopSort\CircularDependencyException: Circular dependency found: modelascontrollerroutes->logviewerconfig->modelascontrollerroutes in C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\CircularDependencyException.php:34
    Stack trace:
    #0 C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\Implementations\BaseImplementation.php(57): MJS\TopSort\CircularDependencyException::create(Array)
    #1 C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\Implementations\ArraySort.php(63): MJS\TopSort\Implementations\BaseImplementation->throwCircularExceptionIfNeeded(Object(stdClass), Array)
    #2 C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\Implementations\ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array)
    #3 C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\Implementations\ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array)
    #4 C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\Implementations\ArraySort.php(115): MJS\TopSort\Implementations\ArraySort->visit(Obje in <b>C:\wamp\www\ss4beta2\vendor\marcj\topsort\src\CircularDependencyException.php</b> on line <b>34</b><br />

The error is gone after `composer remove ....`

It appears that only `silverstripe/config` is dependent on `marcj/topsort`

Travis build failing: https://travis-ci.org/silverleague/silverstripe-logviewer/builds/227422755

**Comment by robbieaverill** [comment]
I've updated the failing builds in #30, but I didn't encounter this problem. Did you upgrade to beta2 from previous versions or was it a fresh install?

**Comment by zanderwar** [comment]
Fresh install :/ WAMP installation

**Comment by Firesphere** [comment]
That sounds like an (old) config.yml error?

**Comment by robbieaverill** [comment]
This shouldn't be happening any more - if it is please feel free to reopen. Thanks for reporting!

**Comment by robbieaverill** [comment]
Note #22 fixed an issue like this from a previous SS alpha release
